### ISSUE TITLE
Provide a way to install rustlings with homebrew

### ISSUE THREAD

**Issue by alimehasin** [rust-lang/rustlings#1082]
Hope to see brew formulae for rustlings

**Comment by Transurgeon** [comment]
@diannasoreil could you assign this issue to me? I would like to try out adding rustlings to homebrew

**Comment by diannasoreil** [comment]
I'm not sure how useful this would be, as installing the command and cloning the repository need to happen at the same time (the command/binary needs to be built from the repository). I don't think it fits what criteria there are for making something installable in Homebrew.

**Comment by Transurgeon** [comment]
Oh ok, no worries then.
I also noticed that the process of installing rustlings was quite different than other casks in Homebrew.

**Comment by tisba** [comment]
nice, thanks @mo8it 👏 Would love to give this a try, but I'm not sure how. Did you add rustlings to homebrew-core? Or is it a custom homebrew tap? 🔍

**Comment by mo8it** [comment]
Sorry for the confusion, but I closed the issue because of its closing words by @shadows-withal in https://github.com/rust-lang/rustlings/issues/1082#issuecomment-1366522384. I don't think that it is worth it, maybe unless we go in the direction of https://github.com/rust-lang/rustlings/issues/1919. Then we would have a standalone binary and wouldn't need the repository.
