### ISSUE TITLE
Print a message if a newer version is available

### ISSUE THREAD

**Issue by beardgans** [rust-lang/rustlings#1111]
👋 Thank you for this awesome project!

I found this feature in the [GitHub CLI application](https://github.com/cli/cli/blob/trunk/internal/update/update.go) and [npm](https://github.com/npm/cli/blob/latest/lib/utils/update-notifier.js).

I think it'll be useful for users who install `rustlings` using the installation script.
And this will let them know that a new version is available and it's time to update.

Ready-made crates to implement that:
* https://github.com/mgrachev/update-informer
* https://github.com/tarikeshaq/update-notifier

**Comment by mo8it** [comment]
I like the idea because I am addicted to running updates 😅 But it is not worth it for Rustlings.
If people already started with the exercises, then they don't need any update (unless something is broken, but in that case they would look for a fix and then maybe update).

It is also unclear how the update should happen. Do we only update the program or also the exercises? Which exercises should we overwrite?

A lot of effort for no significant benefit, especially because you normally install it, solve the exercises and just remove it.

If someone want to refresh some _rusty_ 😅 knowledge, then I would recommend a fresh new installation.
