### ISSUE TITLE
`as_ref_mut.rs`: Unsure about the bigger picture

### ISSUE THREAD

**Issue by magnusrodseth** [rust-lang/rustlings#1156]
This is more of a question / discussion than an issue, so feel free to close it if it does not adhere to the contributing guidelines 😁

I don't quite understand what's going on in the `num_sq` function in the `as_ref_mut` exercise.

Initially, I used the following snippet:

```rust
fn num_sq<T: AsMut<u32>>(arg: &mut T) {
    arg.as_mut().pow(2);
}
```

This did not raise the target value `3` to the power of 2 (`9`).

Then I changed it to the following:

```rust
fn num_sq<T: AsMut<u32>>(arg: &mut T) {
    *arg.as_mut() *= *arg.as_mut();
}
```

I have no problem understanding how the latter snippet works. **However, I don't understand why the former snippet returns `3` instead of `9`?** 

Is it simply because `.pow()` returns a value, and `num_sq` does not? If this is the case, perhaps some work should be done to improve the hints on this exercise.

**Comment by washbin** [comment]
I guess it is mostly clear from the suggestion to use AsMut, as you wouldn't need AsMut if you don't mutate the value, [ I could be wrong on how much clarity it gives though ]

As for why the first snippet didn't work, I guess it will if you mutate the value instead of just finding the power.
As you said, the pow function returns the power so you could assing that as the new value.

Like,

```rs
fn num_sq<T: AsMut<u32>>(arg: &mut T) {
    *arg.as_mut() = arg.as_mut().pow(2);
}
```

**Comment by nugend** [comment]
This exercise could really use a bit more guidance about the what and why you're supposed to choose particular type bounds.

**Comment by Nagidal** [comment]
I could not do this exercise myself. Even when I read all about as ref in the [book](https://doc.rust-lang.org/stable/book/ch17-03-oo-design-patterns.html) and both AsRef and AsMut in the standard library, I'm still completely oblivious what this is all about and where can it be used. It would be nice if the exercise introduced us to a problem, where as_ref or as_mut are the killer features to use. Or present us a scenario, where it would be beneficial to implement AsRef of AsMut.

**Comment by jwillinghalpern** [comment]
`num_sq` feels weird to me too. It was the only exercise in rustlings I couldn't figure out.

Even the solution above feels a little funky because (I think) it says that T must be able to be mutated as a u32, despite being generic? I kept feeling like the real solution should implement another trait like `Mul` without specifying a primitive like u32, but I couldn't figure that out either.

**Comment by aSapien** [comment]
I got stuck there too. What threw me off is the following snippet from the [rust reference](https://doc.rust-lang.org/std/convert/trait.AsMut.html)
```rs
let mut x = Box::new(5i32);
// Avoid this:
// let y: &mut i32 = x.as_mut();
// Better just write:
let y: &mut i32 = &mut x;
```

The above led me to assume that `as_mut()` should not be called directly, and be instead invoked implicitly.
