### ISSUE TITLE
clippy1 passes

### ISSUE THREAD

**Issue by rlpowell** [rust-lang/rustlings#1173]
For me, clippy1 showed up as `🎉 🎉  The code is compiling, and 📎 Clippy 📎 is happy! 🎉 🎉` immediately.

Here's my versions:
```
root@2f0ba9ddef2d:/src/rustlings/exercises/clippy# cargo clippy
    Checking clippy1 v0.0.1 (/src/rustlings/exercises/clippy)
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
root@2f0ba9ddef2d:/src/rustlings/exercises/clippy# cargo --version
cargo 1.64.0-beta.3 (ded089921 2022-08-11)
root@2f0ba9ddef2d:/src/rustlings/exercises/clippy# rustup toolchain list
beta-x86_64-unknown-linux-gnu (default)
root@2f0ba9ddef2d:/src/rustlings/exercises/clippy# cargo clippy --version
clippy 0.1.64 (82bf341 2022-08-18)
```

**Comment by chrisdueck** [comment]
I had the same issue. I'm guessing this is because `float_cmp` is in the `allow` lint level: https://rust-lang.github.io/rust-clippy/master/index.html#/float_cmp.

The error does appear if you run `cargo clippy -- -Dclippy::pedantic`:
```
chris@pc:~/rustlings/exercises/clippy$ cargo clippy -- -Dclippy::pedantic
    Checking clippy1 v0.0.1 (/home/chris/rustlings/exercises/clippy)
error: strict comparison of `f32` or `f64`
  --> clippy1.rs:14:8
   |
14 |     if y != x {
   |        ^^^^^^ help: consider comparing them within some margin of error: `(y - x).abs() > error_margin`
   |
   = note: `-D clippy::float-cmp` implied by `-D clippy::pedantic`
   = note: `f32::EPSILON` and `f64::EPSILON` are available for the `error_margin`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#float_cmp

error: could not compile `clippy1` due to previous error
```

One way to fix it is to update the args used in `exercise.rs`. I've tried it and it works, but it also leads to other unintended "pedantic" clippy warnings (e.g. on the `println!` in `clippy2.rs`).

I think the simplest solution might just be to add something like `#![warn(clippy::pedantic)]` to the top `clippy1.rs` by default. This does the job without affecting any other exercises. I can make a PR for this, but open to any nicer solutions.

**Comment by shadows-withal** [comment]
> I think the simplest solution might just be to add something like #![warn(clippy::pedantic)] to the top of clippy1.rs by default. 

This works for me (for now), and I'd be happy to merge a PR for this.

**Comment by chrisdueck** [comment]
Actually, it looks like an update to clippy1 was already released in [April 2022](https://github.com/rust-lang/rustlings/commit/f2650de369810867d2763e935ac0963c32ec420e) so I guess this shouldn't matter anymore. I had a version of rustlings from before that update was released. Guess we can just close this?

**Comment by shadows-withal** [comment]
oh, fair
