### ISSUE TITLE
Open next practice source code by specified editor

### ISSUE THREAD

**Issue by poly000** [rust-lang/rustlings#1201]
Some IDE allow us to open an source file in current windows if they are in the folder we opened.

For example, rustling run `code exercises/primitive_types/primitive_types3.rs` if user set `RUSTLING_EDITOR` as `code {}` and just finished primitive_types2.

This avoids bad experience switching to next chapter on some IDE.

For `vim` users, to make buffers order as pratices':
```bash
vim `rustlings list|head -n -1|tail -n +2|cut -f 2`
```

**Comment by mo8it** [comment]
Closing because of the comment https://github.com/rust-lang/rustlings/pull/1211#issuecomment-1261961793

It is not worth it and can't work with Terminal text editors like Helix (which I use).

I recommend to just use a shortcut in your editor to open a file quickly. This should be Ctrl+p in VS-Code.
