### ISSUE TITLE
Weird comment on `if1`

### ISSUE THREAD

**Issue by doliG** [rust-lang/rustlings#125]
Hello,

I'm brand new to rust and currently playing with your exercises.
In the `if1` exercicse, it is said in comments that we should not use `return`.

But I don't understand how can it work without a return statement.

For now, here is my solution:
```rust
pub fn bigger(a: i32, b:i32) -> i32 {
    // Complete this function to return the bigger number!
    // Do not use:
    // - return
    // - another function call
    // - additional variables
    // Scroll down for hints.
    if a > b {
        return a;
    }
    else {
        return b;
    }
}
```

I know that Rust has an implicit return system, and I came to this solution too (which I personnaly think that it looks bad)
```rust
pub fn bigger(a: i32, b:i32) -> i32 {
    // Complete this function to return the bigger number!
    // Do not use:
    // - return
    // - another function call
    // - additional variables
    // Scroll down for hints.
    if a > b {
        a
    }
    else {
        b
    }
}
```

Any help/advises are welcome.

**Comment by TomasHubelbauer** [comment]
The last expression in a block is going to be implicitly returned from the block. A method body is a block of statements and expression, the last of which is going to be implicitly returned. I say block instead of method body, because this is a generic statement about Rust blocks. A method body has a "return value" in form of the last expression and so does for example an `if` or `else` block.

In Rust, `if` is not a statement, but an expression, so it has a return value. It acts as a ternary operator. You could for example assign a result of an `if` to a variable, like so: `let result = if a > b { a } else { b }`.

Putting these two axioms together, you will find that `if a < b { a } else { b }` is an expression and as such returns a value and additionally in this case it is a last expression in the method body so its value is going to become the return value of the method.

```rust
pub fn bigger(a: i32, b:i32) -> i32 {
    let implicitReturnValue = if a > b {
        a
    }
    else {
        b
    }

  return implicitReturnValue 
}
```

This is why it works.

**Comment by doliG** [comment]
Thanks a lot for your explanation :) It makes the concept pretty simple to understand!
