### ISSUE TITLE
"watch" is broken on windows

### ISSUE THREAD

**Issue by Hades32** [rust-lang/rustlings#126]
The issue seems to be that the call to verify(...) in main.rs:92 expects the path to be in Unix style (forward slashes instead of backslashes), so the later compare breaks.

I fixed this locally by just doing a string replace, but I guess a true Rustacean will fix this much more nicely so I didn't add a patch.

PS: It's also pretty inconvenient that "watch" doesn't continue with the next exercise once you fix the current one.

**Comment by komaeda** [comment]
@Hades32 it should continue! sounds like it's broken for you, maybe?

**Comment by guttume** [comment]
I faced the same issue with watch on Windows

**Comment by steing** [comment]
reverting to tags/1.0.0 and rebuilding seems to have worked for me.  compiles on save and advances to next exercise.

**Comment by guttume** [comment]
@steing noted. Thank you.

**Comment by sebsebmc** [comment]
I have the same issue and #134 did not fix the problem.

**Comment by cjpearce** [comment]
Happy to give fixing this a go if it's still broken. I have a windows vm I can debug in.

**Comment by komaeda** [comment]
@cjpearce That would be much appreciated! I'm honestly a bit stuck on this issue as I have neither the time or the resources to get going on this

**Comment by sebsebmc** [comment]
I've been debugging the issue and I believe that the problem is that the paths that notify is returning look something like `..../exercises\\variables\\variables1.rs` but the value in info.toml looks like `exercises/variables/variables1.rs` so the `ends_with` comparison here always fails: https://github.com/rust-lang/rustlings/blob/04d1d4c00ee9c74d64734ef9880607599830286d/src/verify.rs#L16 

I believe the solution may require using something like http://github.com/BurntSushi/same-file 

I have a pretty ugly patch that canonicalizes both paths for comparison and that seems to work on Windows, haven't tested it on Linux yet. I'm hoping there may be a more elegant solution.

**Comment by cjpearce** [comment]
@sebsebmc That's in line with what I've found too. I think that `canonicalize()` might be a pretty good solution, since that path really needs it. But I absolutely agree gets pretty messy if we start constructing and then canonicalizing the strings just before we use them.

I think one way of fixing this is to deal with constructing canonicalized the paths up front before we get into any of the logic. I'm working on a PR that would clean up how we handle the paths, which hopefully will mean it doesn't become as messy. I should have it something to show in the next day that we could test.

If you get to a solution you're happy with first I'd be happy to help on that too.

**Comment by sebsebmc** [comment]
https://github.com/rust-lang/rust/issues/42869 has a discussion on canonicalization on Windows.

I looked up some projects that use notify and found that [alacritty](https://github.com/jwilm/alacritty) and [xi-editor](https://github.com/xi-editor/xi-editor/) both do canonicalization for their paths.

There is https://github.com/rust-lang/rfcs/issues/2208 that could potentially be used in the future if it ever lands, but it seems like canonicalization should be fine and is expected to work.
