### ISSUE TITLE
Vecs2 - unclear for what to do on second example with .map |num|

### ISSUE THREAD

**Issue by Darkstar130** [rust-lang/rustlings#1444]
It's not explained along the course when coming to the issue on what to write in 

fn vec_map(v: &Vec<i32>) -> Vec<i32> {
    v.iter().map(|num| {
     // TODO: Do the same thing as above - but instead of mutating the
     // Vec, you can just return the new number!
}).collect()

The readme points to 8.1 but the second example requires understanding what's in 13.2 in the rust docs. Suggestion is to add 13.2 to the readme or more clarity to vec_map comments

**Comment by mo8it** [comment]
I modified the exercise in the [v6 branch](https://github.com/rust-lang/rustlings/blob/v6/exercises/05_vecs/vecs2.rs):
- Instead of mutating a vector in the first function, now an empty vector is created and new elements are pushed to it. This provides a better comparison to the second method with iterator mapping and then collecting. Because mutation doesn't involve allocation and collecting the iterator allocates.
- I added an example for the method with the iterator.
- I improved the comments.

I can reopen the issue if someone is still not satisfied with the new version.
