### ISSUE TITLE
Check not only code output but also code itself

### ISSUE THREAD

**Issue by Mart-Bogdan** [rust-lang/rustlings#1677]
Examaple if1  requires you to use IF instead of standard function, but it is not enforced

![image](https://github.com/rust-lang/rustlings/assets/775038/ef0d39c7-7e08-4a9e-9612-9c78575250e7)

I also noticed similar cases in variables, where I was able to add `mut` instead of creating new binding that is shadowing old binding. Etc.

**Comment by Mart-Bogdan** [comment]
It also don't assert output

![image](https://github.com/rust-lang/rustlings/assets/775038/8499d94d-0b84-4af4-8e4f-445435e60093)

**Comment by mo8it** [comment]
Closing in favor of https://github.com/rust-lang/rustlings/issues/293

I don't think that we should try to enforce solving the exercises more than we currently do.
1. Parsing and checking code can quickly get very complicated. We leave this task to the compiler and the linter Clippy.
1. If the user "cheats" or just takes a shortcut, no harm is done since this is not an exam :P
1. It would be much better to provide a solution so that the user sees how the exercise was actually meant to be solved.
