### ISSUE TITLE
Vectors are before Structures?

### ISSUE THREAD

**Issue by arthurkarganyan** [rust-lang/rustlings#1787]
I'm new to Rust and I'm reading the Rust book and doing the rustlings exercises in parallel. And they seem to match the order of covered topics. However, the Vector chapter is number 8 in the book and Structures chapter is number 5, but in rustlings Vectors appear before Structures. I know, it's not a big deal, but maybe the order should be changed, I don't know.

**Comment by arthurkarganyan** [comment]
The same for enums

**Comment by ArmoredPony** [comment]
As a newbie, I still have to learn arrays just in case I run into them later. Some examples of `arrays` instead of `vecs` at this point (after `primitive_types`) would've been very welcome. And instead of vectors in `move_semantics` Strings could be used, like they are used in The Book to explain ownership and moving.

**Comment by mo8it** [comment]
Closing based on the comment https://github.com/rust-lang/rustlings/issues/1787#issuecomment-1832297807
