### ISSUE TITLE
cargo test issue with `I AM NOT DONE` annotation in "exercises ..

### ISSUE THREAD

**Issue by saingsab** [rust-lang/rustlings#1811]
Also ready remove the  `I AM NOT DONE` but didn't pass the test and it's occur bellow
` There should be an `I AM NOT DONE` annotation in "exercises`

Not sure if everyone face the same issue as me.

**Comment by matthri** [comment]
Hi,
I am assuming you are doing the Rustlings exercises and don't develop on the Rustlings project itself. 

The Rustlings exercises are a bit special when it comes to the project structure. 
To run the exercises you use the `rustlings` executable which will compile and run the exercise for you.

You can either run a single exercise using the `rustlings run` command  or use the `rustlings watch` command which automatically watches and recompiles the next unfinished exercise.
To run a single exercise use `rustlings watch` followed by the exercise name, to e.g. run the `intro1` exercise you can use the `rustlings run intro1` command.

For more information on how to run the Rustlings exercises see [the README](https://github.com/rust-lang/rustlings#doing-exercises)

The `cargo test` issue you are facing is because the tests are for the development of the Rustlings project and the associated `rustlings` executable. 
The failing test is the one which checks if all tests contain a `I AM NOT DONE` comment, to make sure all exercises are in a "unsolved" state when published.

**Comment by saingsab** [comment]
Thank you so much, I think I just get to understand better about the rustlings structure.
