### ISSUE TITLE
variables3.rs -> println seems to ignore datatype if variable is given a value as parameter.

### ISSUE THREAD

**Issue by dataCobra** [rust-lang/rustlings#1932]
Hey,

I'm currently reading the Rust book and try out the rustlings exercises for each chapter.

I was just fiddling a bit with the exercise and came across a situation that I don't understand.

I've set x to be `i8` instead of `i32` so a positive value above 127 shouldn't be allowed.

Everything works as expected when I give `x` a value in main scope, but when `x` got a value while using at as a parameter for `println!` it seems to ignore my chosen data type.

This shouldn't compile as far as I'm understanding it.

```rust
fn main() {
    let x: i8;
    println!("Number {}", x = 1000);
}
```

I really don't understand what is happening here.

Some clarification would be much appreciated.

**Comment by mo8it** [comment]
Hi Benedikt,

when I compile your snippet in a normal Rust project, I get the following two warnings:

```
warning: named argument `x` is not used by name
 --> src/main.rs:3:27
  |
3 |     println!("Number {}", x = 1000);
  |                      --   ^ this named argument is referred to by position in formatting string
  |                      |
  |                      this formatting argument uses named argument `x` by position
  |
  = note: `#[warn(named_arguments_used_positionally)]` on by default
help: use the named argument by name to avoid ambiguity
  |
3 |     println!("Number {x}", x = 1000);
  |                       +

warning: unused variable: `x`
 --> src/main.rs:2:9
  |
2 |     let x: i8;
  |         ^ help: if this is intentional, prefix it with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default
```

What is happening here is that you are declaring a new variable `x` to be used inside the `println!` macro. The compiler tells you that the actual variable that you declared (`let x: i8`) is not used at all. The variable `x` was [shadowed](https://doc.rust-lang.org/rust-by-example/variable_bindings/scope.html).

Assignments in formatting macros like `println!` are designed as an alternative to positional arguments so that you can do something like

```rust
println!("{x} and {x}", x = 1000);
```

instead of

```rust
println!("{} and {}", 1000, 1000)
```

What you expect is the following:

```rust
fn main() {
    let x: i8 = 1000;
    println!("Number {x}");
}
```

This doesn't compile as you expected.

**Comment by dataCobra** [comment]
Thank you! :)
