### ISSUE TITLE
Help to pass vecs2.rs

### ISSUE THREAD

**Issue by Maxencoubidou** [rust-lang/rustlings#1954]
Hello,

I'm stuck on the vecs2.rs for one week now.
The problem is on the second loop of the training.
I don't understand what I have to do to pass the exercise.

Thank you for your help !

**Comment by mo8it** [comment]
You don't need any `for` loop in the second function (`vec_map`). In fact, iterators are an alternative to `for` loops. You just need to write `2 * element`:

```rust
v.iter()
    .map(|element| {
        2 * element
    })
    .collect()
```

This basically says that you want to map each element in the vector to its double.

Struggling with iterators is totally normal since they aren't wide spread in other languages. You are welcome to ask for help earlier next time. You don't need to wait one week 🤗
