### ISSUE TITLE
What happened to nix?

### ISSUE THREAD

**Issue by MatthiasvB** [rust-lang/rustlings#2054]
As a nix user, I was just wondering if perhaps rustlings could be installed in nix enabled environments. There are a bunch issues here that discuss [adding a nix config](https://github.com/rust-lang/rustlings/issues/683) and then later ones describing problems with it. But _now_ no nix specific config or documentation is around. What happened?

**Comment by mo8it** [comment]
Rustlings can be installed with Nix. You install it with `cargo install rustlings`.
So you need to have `cargo` installed. I tested it in a container with the following:

```bash
nix-env -iA nixpkgs.rustup nixpkgs.gcc
rustup default stable
cargo install rustlings
~/.cargo/bin/rustlings # Better add ~/.cargo/bin to your PATH
```

After making Rustlings a self-contained binary in version 6, I removed the outdated Nix files. I will not add anything that I can't maintain because I don't use Nix. If people want to use Nix, they should figure out how to install Rust and do `cargo install`.

**Comment by Brisingr05** [comment]
Note for Nix users: rustlings is now in Nixpkgs (track the [PR](https://github.com/NixOS/nixpkgs/pull/334610) [here](https://nixpkgs-tracker.ocfox.me/?pr=334610)).
