### ISSUE TITLE
`rustlings` crashes when `solutions/` doesn’t exist

### ISSUE THREAD

**Issue by mikeocool** [rust-lang/rustlings#2068]
Rustlings Version: 6.1.0

Repro Steps:

* Run `rustlings init`
* Delete `solutions/`
* Run `rustlings` 

Result:
* The intro message will show, but when you press enter the process exits immediately with exit code 1.

This came up for me, because after running `rustlings init` — I committed my progress, pushed the git repo create to a remote, and then cloned that repo it on another machine to continue working. `solutions` is included in the created .gitignore file, so it wasn’t present in the cloned repo — when attempting to run `rustlings` to continue, it crashed.  Should solutions maybe just not be included in .gitignore, so that the directory gets committed?

**Comment by mo8it** [comment]
Fixed in https://github.com/rust-lang/rustlings/commit/97719fe8da82a91a1919e55e1950d0997acca574

BTW, Rustlings didn't crash in that case. It attempted to show an error message, but the error message was cleared away with the terminal clearing after showing the welcome message. Funny issue! Fixed in https://github.com/rust-lang/rustlings/commit/11fc3f1e56b1b248465039db4c736bb7186e4f47
