### ISSUE TITLE
Make the list searchable

### ISSUE THREAD

**Issue by frroossst** [rust-lang/rustlings#2093]
When pressing `l` to bring up a list of exercises, I think it'd be a neat idea to press `/`and start searching, similar to vim. 

If there is  interest in this feature, I'd like to take a crack at implementing it. Thanks!

**Comment by mo8it** [comment]
Good idea! You are welcome to implement it in a PR :D

Here are some tips for getting started:
- Handle the input `l` here: https://github.com/rust-lang/rustlings/blob/ea52c99560119070cb2c82c65dd92017240c5071/src/list.rs#L35
- Add `Option<String>` to `ListState`: https://github.com/rust-lang/rustlings/blob/ea52c99560119070cb2c82c65dd92017240c5071/src/list/state.rs#L37. `None` means that there is no active search. `Some(s)` means that the user is searching for an exercise containing `s` in its name.
- Extend the exercise iterator filter before displaying the rows: https://github.com/rust-lang/rustlings/blob/ea52c99560119070cb2c82c65dd92017240c5071/src/list/state.rs#L198-L204
- Add that filter to the selection logic as well: https://github.com/rust-lang/rustlings/blob/ea52c99560119070cb2c82c65dd92017240c5071/src/list/state.rs#L332-L354

Don't add any additional crates. `O(N)` shouldn't be dramatic here. I don't think that Rustlings will be ever used on more than 150 exercises.

No fuzzy search, just use [`str::contains`](https://doc.rust-lang.org/stable/std/primitive.str.html#method.contains).

If you need any help, feel free to ask me :)

**Comment by mo8it** [comment]
(_I deleted my comment because I have a better idea of how to implement it now_)

Good idea! You are welcome to implement it in a PR :D

I added `<s>earch` to the help footer in https://github.com/rust-lang/rustlings/commit/75a38fa38b65c075f34233f4745eb6d1d7405a39. So we should trigger a search by `s` and `/`.

Here are some tips for getting started:
- Handle the input `s` and `/` here: https://github.com/rust-lang/rustlings/blob/ea52c99560119070cb2c82c65dd92017240c5071/src/list.rs#L35
- Add a `String` field to `ListState` which contains the search input: https://github.com/rust-lang/rustlings/blob/ea52c99560119070cb2c82c65dd92017240c5071/src/list/state.rs#L37
- During search, you need to handle any input char you get and add it to the search string.
- When search is triggered, replace the 2 footer lines with `search:│`. Use the unicode char `│` to indicate the cursor. Then you update it after each input, so searching for `quiz1` should look like `search:quiz1│`.
- Use `set_selected` to select the first exercise that contains the search input string (if any is found): https://github.com/rust-lang/rustlings/blob/75a38fa38b65c075f34233f4745eb6d1d7405a39/src/list/scroll_state.rs#L49
- No fuzzy search, no regex, just use [`str::contains`](https://doc.rust-lang.org/stable/std/primitive.str.html#method.contains) on the exercise name.
- Entering `ESC` or `ENTER` should stop searching.

This means that searching doesn't filter. It should just jump to the first exercise that contains the search input. This makes things much easier than filtering.

Don't add any additional crates. `O(N)` shouldn't be dramatic here. I don't think that Rustlings will be ever used on more than 150 exercises.

If you need any help, feel free to ask me :)

**Comment by frroossst** [comment]
Thank you for the guidance, I will start implementing it, and file a PR.

**Comment by frroossst** [comment]
I have the code in working order.

- Pressing enter exits the search and returns you out of the list (maybe enter shouldn't do that?)
- Made set_selected() in ScrollState public, maybe some other helper function can be used?

There is a clippy lint that is failing, I'm trying to figure out why. And do you want all the commits to be squashed into one?

Thanks for this opportunity to contribute!

**Comment by mo8it** [comment]
- No, pressing enter or ESC shouldn't exit the list, only the search.
- I was expecting you to make it public. No problem at all.
- No, I hate squashing commits. Every commit contains information that shouldn't be lost.
- One problem: You need to filter exercises depending on `self.filter` before getting the index of the selected one. So maybe `iter().filter(…).position(…)`

I will review again after fixing these points. But it already looks very well implemented! :D

**Comment by frroossst** [comment]
I have made the suggested changes. Please take a look whenever you have time.

And thank you for the compliment, this is my first time contributing a feature to any open source project! <3

**Comment by mo8it** [comment]
WOW, the first time? It is very pleasant to work with you. You are very welcome to keep contribute to Rustlings :D

**Comment by mo8it** [comment]
I posted a demo on Mastodon and mentioned you: https://fosstodon.org/@mo8it/113076241056507589
