### ISSUE TITLE
rustlings watch does nothing when all exercises are complete

### ISSUE THREAD

**Issue by codehearts** [rust-lang/rustlings#251]
I just completed everything in 2.1.0 and `rustlings watch` showed that my threads1 solution compiled, but no other output was shown. I assumed my solution was running but hit a deadlock or something, but 15 minutes later I realized `watch` does nothing when you're done

It'd be nice to display a congratulatory message so we can feel accomplished and know when we're done! 😸

**Comment by AbdouSeck** [comment]
@codehearts this could be a very good feature, indeed. If you want to implement it, go for it. It's fairly manageable.
If you don't know where to start because you're not familiar with the project, I am happy to point you in the right direction and work with you to get it done. Let me know what you think.

Thanks,

Abdou
