### ISSUE TITLE
Provide a reference solution after finishing an exercise

### ISSUE THREAD

**Issue by Tuxified** [rust-lang/rustlings#293]
Hi,

I really enjoyed the current exercises (version 2.2.1), thanks for your efforts!
While I managed to finish all exercises, there were some exercises for which I felt there could be better, more idiomatic solutions. 

Hence I was hoping a repo with examples would be provided or a way to "grade" my solution according community standards?

**Comment by sjmann** [comment]
Maybe this can be handled in a similar way to [Clojure by example](https://github.com/inclojure-org/clojure-by-example/)? They have a branch on github where all the solutions are solved.

It would probably take a while for it to grow organically as it would require experienced rustaceans to have a look at the solutions and make sure they're fully idiomatic, but I would be happy to start contributing my own solutions to such a branch as a starting point if it existed (although they would almost certainly have imperfections that would need to be ironed out).

**Comment by peterkos** [comment]
Maybe a dedicated website that's more blog-style that discusses solutions and their permutations? For a few of these I've found different ways to solve them, and it'd be cool to have an explanation for why someone would choose each approach. 
Of course this could quickly turn into a rewrite of the Rust book lol. But some kind of guidance might be interesting nevertheless!

**Comment by peterkos** [comment]
I'd be open to creating a video series but I think that a website would be easier to digest and _especially_ easier to update over time.

**Comment by ChristopherBiscardi** [comment]
> I'd be open to creating a video series

I actually already did this! It should be published soon but all the videos are recorded for every exercise in 3.0. I have a couple more to do now that 4.0 has been released, but that looks like ~5 or so new videos on top of 3.0.

**Comment by jayber** [comment]
I think this and #820 are the same great idea!

Wouldn't the easiest thing for _anyone_ of the core maintainers, or really anyone who has successfully completed the course to check their code into an examples directory parallel to the exercises directory? They don't need to be perfect, though probably reviewed as acceptable and can be updated with alternatives by anyone. Because this is quick and easy it is more likely to get done. I mean, I could do this today, simply because I finished the course yesterday :-)

**Comment by mo8it** [comment]
Hi, a new maintainer here :D

I definitely like this idea of showing a solution after finishing an exercise. I would love to work on it but I would prefer that the solution is shown only when the exercise is done.

If we go in the direction of https://github.com/rust-lang/rustlings/issues/1919, then we can put the solutions in the same repository since you wouldn't have a direct access to the repository anymore while you are working on the exercises.
When an exercise is done, the solution file will be placed in a `solutions` directory next to the `exercises` directory :D
