### ISSUE TITLE
exercises on unsafe?

### ISSUE THREAD

**Issue by sanjaykdragon** [rust-lang/rustlings#380]
Title says all. I was thinking of making some exercises on some unsafe rust features, but not sure because ATM this seems to be a beginner course. Opinions?

**Comment by mo8it** [comment]
Closing because I don't think that beginners (the target audience of Rustlings) should experiment with `unsafe`.

In addition, Rustlings is aligned with the official Rust book which has [only one "page" on unsafe](https://doc.rust-lang.org/stable/book/ch19-01-unsafe-rust.html).
Advanced users that want to dig into unsafe would need to read the [Rustonomicon](https://doc.rust-lang.org/nomicon/).
