### ISSUE TITLE
Option1 requires a somewhat obscure array initialization

### ISSUE THREAD

**Issue by sirxyzzy** [rust-lang/rustlings#395]
In option1.rs, I have to initialize the mutable array to suppress the following error:

error[E0381]: use of possibly-uninitialized variable: `numbers`
  --> exercises/option/option1.rs:22:9
   |
22 |         numbers[iter as usize] = Some(number_to_add);
   |         ^^^^^^^^^^^^^^^^^^^^^^ use of possibly-uninitialized `numbers`

error: aborting due to previous error; 1 warning emitted

Instead of ```let mut numbers: [Option<u16>; 5];``` I need to use ```let mut numbers = [Some(0); 5];```

IMO the compiler should be able to deal with an uniitialized array here as it knows the values of iter, but that doesn't seem to be the case, at least on on rustc 1.45.0-nightly (bad3bf622 2020-05-09)

**Comment by ZaynChen** [comment]
>the compiler should be able to deal with an uniitialized array here as it knows the values of iter

I think the error is not caused by `iter`, but by 
>It is not allowed to use or capture an uninitialized variable.
  -- rustc --explain E0381

The compile treats `numbers[iter as usize] = Some(number_to_add);` as binding `Some(number_to_add)` to `numbers[iter as usize]`, which is using `numbers`, not initializing it. So it failed as `numbers` hasn't been initialized at that point.The statement `let mut numbers: [Option<u16>; 5];` just declares `numbers`, and has nothing to do with initialization. 
>It's possible to declare variable bindings first, and initialize them later. However, this form is seldom used, as it may lead to the use of uninitialized variables.
The compiler forbids use of uninitialized variables, as this would lead to undefined behavior.
-- [Rust By Example](https://doc.rust-lang.org/stable/rust-by-example/variable_bindings/declare.html)

**Comment by sirxyzzy** [comment]
Thanks for taking the time to explain, much appreciated. I won't argue the point regarding whether the compiler message makes sense (although we must agree to disagree), but to have this as a problem to fix in a Rustling about use of Option makes the exercise difficult to complete. It was a fascinating learning exercise, in a general kind of sense, but hardly pertinent to Option itself

**Comment by jacktrusler** [comment]
This was great as a budding rustling myself. It led me to this [great article on array initialization](https://www.joshmcguigan.com/blog/array-initialization-rust/). 

For anyone still confused about the question itself, the error can be fixed by initializing the array: `let mut numbers: [Option<u16>; 5] = [None; 5]`
