### ISSUE TITLE
Clear up the exercise as_ref_mut

### ISSUE THREAD

**Issue by dev-cyprium** [rust-lang/rustlings#404]
Hello,

I've been trying to solve exercise `as_ref_mut.rs` for some time now, and I'm unable to figure out how to properly note the function signature to make it work. I'm a beginner in rust who just finished the book and wanted to just jump into some code.

So the reason I'm stuck is because of the generics, and in the linked exercise documentation [AsRef](https://doc.rust-lang.org/std/convert/trait.AsRef.html) it only covers usage with concrete type `&str`.

So my guess was trying something like:
```rs
fn byte_counter<T: AsRef<&T>>(arg: T) -> usize {
  // ...
}
```

which didn't work, as it was expecting lifetimes.

Finally I opted-in for the hint and realized the solution is simply to use `AsRef<str>`. 

So in this particular case, what's the advantage of using a ref here as opposed to just a `&str` reference?

If I simply write:
```rs
fn byte_counter(arg: &str) -> usize {
 // ...
}
```

It's still gonna work for both `String` and `&str` due to **deref coercion**:
```rs
byte_counter("a slice");
byte_counter(String::from("a String"));
```

so what's the point of having a trait `AsRef`? After doing the exercise I honestly still can't wrap my head around the actual concept behind the reason why this trait exists and how one might actually use it?

**Comment by AbdouSeck** [comment]
Hi @dev-cyprium, using `AsRef` is definitely not the only way to solve this problem. The same thing could be said about a lot of problems in life in general.

Anyway, there are two points to using `AsRef`:
1. Cheap reference-to-reference conversion (definitely cheaper than value-to-value conversion)
2. An easy way to pass a reference of one type and operate on a completely different type

You are right to be frustrated with the generics bit. But keep in mind that the type system in Rust heavily relies on _**trait bounds**_ to reason about generic functions and types. Otherwise, it would be impossible to have any type safety when it comes to writing generic code. In sum, generics and traits do go hand in hand.

Your generic example would not work mostly because the type `T` is defined nowhere. When you say `<T: AsRef<&T>>`, you're setting bounds for the `T` but those bounds also require `T`.

Also, defining the function with `fn byte_counter(arg: &str) -> usize {}` will not work with `String`. It may work with `&String` though. But with `fn byte_counter<T: AsRef<str>>(arg: T) -> usize {}`, you could pass `&str`, or `&String`, or `String` and any of those would work.

Here is a somewhat better example. Say you wanted to count the number of components in a given file path. You can split the file path on the path separator, and then call `count` on the `Iterator` from this split operation. But you can do better than that by using the `std::path::Path` type because it has a `.components` method that yields an `Iterator` whose `count` you can invoke. If you defined your function to expect a `Path` type, then you would have to convert your strings to `Path` before passing them to your function. With `AsRef`, you don't need to do that. The following should work:

```
use std::path::Path;

/// Count the number of components in a given file path
fn count_components<P: AsRef<Path>>(path: P) -> usize {
    path.as_ref().components().count()
}

fn main() {
    let s1 = "/root/app/src/main.rs";
    let s2 = String::from("/root/app/src/main.rs");
    let p = Path::new("/root/app/src/main.rs");
    assert_eq!(count_components(s1), 5);
    assert_eq!(count_components(&s2), 5);
    assert_eq!(count_components(s2), 5);
    assert_eq!(count_components(p), 5);
}
```
This is the same idea behind the associated function `std::fs::File::open`. The latter can take all sorts of string types along with `Path` and `PathBuf` types.

The trait definitely has its place in the standard library. But if you find yourself not being able to wrap your head around its usefulness, it's likely that you don't need it yet. If you're ever in a situation where reference-to-reference conversion matters, and multiple types should be handled by the same function, then it may be worth giving `AsRef` a try.

I hope this helps clarify things a little.

Abdou

**Comment by dev-cyprium** [comment]
Actually, you've pretty much covered a bunch of confusing bits for me. Appreciate it

Cheers
