### ISSUE TITLE
no error squiggles in VS Code with rls-vscode extension

### ISSUE THREAD

**Issue by DeadRabbits307** [rust-lang/rustlings#443]
VS Code: 1.45.1
OS: 4.19.118-1-MANJARO
rls-vscode: 0.7.8

Creating a new crate/workspace like shown [here](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) the error squiggles work fine. But opening the root directory of rustlings (directory where Cargo.toml is located):
- no error squiggles
- no problems in the PROBLEMS window, despite of code errors

Is this a problem of the rustlings project directory structure? Opening src/main.rs and editing it, the error squiggles appear. Sorry if this topic isn't related to rustlings itself, it's my first time in the Rust world.

**Comment by danwilhelm** [comment]
Luckily, a Cargo workspace is already set up for you -- so you won't have to make your own.

The general procedure is:
1. First, build and install the Rustlings CLI program: `cargo install --force --path .`
2. Edit the exercises in any text editor.
3. Use the Rustlings CLI program to check your answers.

If you still have problems with the VS Code extension, it might be best to ask on the Rust Discord (https://www.rust-lang.org/community).

**Comment by jrvidal** [comment]
Unfortunately, it is half-expected. I think `rls` (and similar tools, like `rust-analyzer`) expect a [conventional project structure](https://doc.rust-lang.org/cargo/guide/project-layout.html), imposed by `cargo`, to be able to effectively analyze your code. `rustlings` on the other hand departs from that structure for pedagogical purposes, so each exercise is completely isolated. Not sure if IntelliJ Rust suffers from the same limitations (note that they [adapted `rustlings`](https://blog.jetbrains.com/blog/2019/12/19/rustlings-course-adaptation/)).

@fmoko Do you think it'd be worth exploring the possibility of changing the structure of the exercises so cargo can understand them? Not sure if "no analyzers" is a bug or a feature...?

**Comment by fmoko** [comment]
@jrvidal Hmm, I think it'd be at least worth trying. Maybe we can branch out, change the structure, see if the analyzer hints spoil some of the exercise solutions, and if they don't, we can merge it in?

**Comment by Farzy** [comment]
Hi @jrvidal I had the same issue with Rust in IntelliJ IDEA Ultimate very recently: no hints and some missing autocompletion IIRC. I haven't tried to circumvent it, maybe there's a trick.

**Comment by jsejcksn** [comment]
What if there were a Rustlings argument specifically for this purpose? One which works with `watch` and `verify` and recognizes the capabilities of editor linting and live file reference updates...

_(Bear with me as I explain: I've done some basic testing, but I don't know the internals of Rustlings. Also, I'll use VS Code as the example IDE, but it's just the example and this could potentially apply to any IDE)_

Instead of the user having edit each exercise directly, Rustlings could create a symlink (for example, `exercises/current.rs`) to the "currently active" (not meeting passing criteria) file, and the user can simply open and continue to edit that `current.rs` file, saving changes along the way. When the linked file finally passes, Rustlings would update the symlink to point to the new "currently active" file. (Perhaps in some OS-editor environment combinations, this symlink strategy isn't possible, and Rustlings would need to create a real `current.rs` file and synchronize content changes with the "currently active" file. I've only tested in VS Code on macOS, and the symlink strategy works fine.)

## UX improvements

- 💆 Not needing to locate, open, and close a file every time a new exercise/quiz is started
- 🙅🏋️ Avoiding the [heft and complexities](https://github.com/rust-lang/rustlings/pull/448#issuecomment-656415410) introduced by constantly analyzing every exercise as a binary target
- 🔬 Displaying only relevant issues in the VS Code Problems panel (instead of all problems in the entire exercises directory and their dependencies—caveat: the `exercises/tests` folder might need to be renamed so cargo doesn't think it contains integration tests. Otherwise, its contents will continue to be reported perpetually.)

## Usage

`exercises/Cargo.toml` would contain something like this:

```toml
[package]
name = 'exercises'
version = '0.1.0'
edition = '2018'
authors = ['The Rustlings Maintainers']
publish = false

[[bin]]
name = 'current'
path = 'current.rs'
```

If using `watch`:

1. Run `rustings watch --ide` (or whatever arg name is decided)
2. Open `$RUSTLINGS_DIR/exercises` in VS Code (to create a workspace in which the Rust extension recognizes `exercises/Cargo.toml` as the project config)
3. Open `current.rs`
4. Edit, save
5. If the file passes, the content is automatically replaced by the new "current" exercise/quiz. Go to step 4.

If using `verify`:

1. Open `$RUSTLINGS_DIR/exercises` in VS Code (to create a workspace in which the Rust extension recognizes `exercises/Cargo.toml` as the project config)
2. Open `current.rs`
3. Edit, save
4. Run `rustlings verify --ide` (or whatever arg name is decided)
5. If the file passes, the content is automatically replaced by the new "current" exercise/quiz. Go to step 3.

**Comment by jrvidal** [comment]
I fear that toying with symlinks and manipulating the file system will introduce more complexity that we can chew. I'm not sure how mature rust-analyzer, for instance, is with regards to its VFS implementation, I'm not sure swapping the content of files will work as seamlessly as we would like.

I'm personally inclined to, instead of going too far with editor integration, perhaps exposing enough metadata so other folks/plugins can integrate easily with the curricula.

**Comment by jsejcksn** [comment]
> I fear that toying with symlinks and manipulating the file system will introduce more complexity that we can chew. I'm not sure how mature rust-analyzer, for instance, is with regards to its VFS implementation, I'm not sure swapping the content of files will work as seamlessly as we would like.

I realize my setup is just a single configuration amongst many.

Tests can provide the information needed to know if these are real problems and will surface some of the details needed to evaluate the cost of potential solutions.


> perhaps exposing enough metadata so other folks/plugins can integrate easily with the curriculum.

Can you expand more on this?

**Comment by jrvidal** [comment]
> Can you expand more on this?

It was mostly a random thought inspired by the aforementioned Jetbrains packaging of Rustlings. I think creating those highly-integrated experiences in your editor of choice might not be too difficult, given the metadata in the `info.toml` file, and I'd be keen to make life easier for packagers.

**Comment by jsejcksn** [comment]
@jrvidal What kinds of metadata were you thinking about besides the ordered list of exercises/quizzes? For example, an integration would need to know which exercise is the "current" one, (or a listing of all with passed/failed status for each). How might that kind of state be managed and provided?

**Comment by nealmcb** [comment]
Note also a rather different approach to "integration" with "IDEs" like emacs and vim and other editors at #281, which at least makes it easy to locate and open the next exercise in most any editor.

**Comment by jackos** [comment]
If using `rust-analyzer` here is a solution: https://gist.github.com/jackos/7332fa8ab0b67a87f382fd566696f412

**Comment by mo8it** [comment]
Closing because the `rustlings lsp` command now exists as @jackos pointed out :D

**Comment by alelom** [comment]
Not sure where it's best to  comment this, but it would be useful to mention `rustlings lsp` in the main ReadMe.md of Rustlings. As a total beginner that decided to start his Rust journey with Rustlings, I only guessed that I was missing key functionality of the `rust-analyzer` Intellisense after a few days (and almost got thinking it was a poor analyzer)!
