### ISSUE TITLE
How to use additionnal crate ?

### ISSUE THREAD

**Issue by qdelettre** [rust-lang/rustlings#454]
Hi,

I'm a rust & rustlings beginner, and i want to use the itertools crate in from_into.rs .
I added it to cargo.toml & did a new build, but still when running rustlings i get the warning 
```
use itertools::Itertools;
^^^^^^^^^ maybe a missing crate `itertools` 
```

At some point, my goal is to collect a tuple from a &str vec in from_into.rs
```rust
let v: Vec<&str> = s.split(',').collect();
if let Some((name, age)) = v.iter().collect_tuple() {
     // continue ...
} else {
    return Person::default();
}
```

Thanks for the tool, and the help :)

**Comment by jrvidal** [comment]
I'm afraid that won't be easy within the rustlings framework, as it is designed for purely self-contained exercises. All of them are solvable using just the primitives from the standard library.

If you still want to use a external crate as an experiment, you can do something like:
```
cargo new rustlings-experiment
cp $YOUR_RUSTLINGS_INSTALLATION/exercises/$YOUR_PARTICULAR_EXERCISES src/main.rs
cargo run
```
with maybe some tweaking required depending on the type of the exercises (maybe `cargo test`, maybe overwrite `src/lib.rs` instead of `main.rs`)

**Comment by qdelettre** [comment]
Thx for the tips @jrvidal . 
I'm gonna save me time and I will do it with the standard library 👍
