### ISSUE TITLE
variables2 hint refers to type of '10'

### ISSUE THREAD

**Issue by monuszko** [rust-lang/rustlings#515]
Whe whole program:
https://github.com/rust-lang/rustlings/blob/main/exercises/variables/variables2.rs

The last line of the hint is:

`What if x is the same type as 10? What if it's a different type?`

How is a newbie supposed to know what type of 10? I completed Rustlings 1.2.1 a while ago and I don't even remember how to display the type of 10. All I know for sure is that I can set the type of x. One might assume that if x is initialized as u32 the literal 10 might get initialized as u32, and if x is initialized as i32 10 might get initialized as i32. My point is that at this stage, which is very second rustling exercise, a newbie likely can't answer the question. The closest I can come up with at the moment is introducing a second variable, y. Is this how I'm supposed to explore the exercise and compiler's treatment of variables?

**Comment by AbdouSeck** [comment]
Hi @monuszko thanks for raising this issue. While I agree that that last line of the hint is quite confusing, I think the exercise itself should be fine, the way it is. This is mostly because the literal `10` does not get a _specific_ type until after a type has been inferred for `x`. This means that it doesn't matter whether `x` is `u8`, or `i8`, or `u16`, or `i16`, or `u32`, or `i32`, etc. As long as an `integer` type is inferred for `x`, the compiler will set that type as the type for `10`. So, it should not matter which integer type it ends up being as long as the literal value `10` can be inferred as that type without error.

To answer your question, you don't need to introduce a second variable. What you need to understand is that the rust compiler does type inference wherever possible. So, in this case `10` is an `integer` and `x` must be an `integer` in order for the `==` operator to work between them.

I hope this helps.

Thanks,
Abdou
