### ISSUE TITLE
`as_ref_mut` not ran

### ISSUE THREAD

**Issue by AntonOellerer** [rust-lang/rustlings#585]
Hey,
First of all, thank you very much for this instructive course, which helped me to get back into rust very fast.
I noticed that, when I finished the second-to-last exercise, `from_str`, that `rustlings watch` immediately told me that I was finished, although I did not touch `as_ref_mut`. Do you know why that might be?
I am running rustlings 4.1.0 and rustc 1.47.0
Best regards
Anton

**Comment by AbdouSeck** [comment]
Hi @AntonOellerer thanks for bringing this up. I am not able to reproduce this issue. I have used `rustlings run as_ref_mut` on both versions `4.1.0` and `4.2.0`. My `rustc` is also `rustc 1.47.0 (18bf6b4f0 2020-10-07)`.

But can you please try all the the following and report your findings?

- `rustlings run as_ref_mut` => This should tell you whether or not the exercise is solved
- `rustlings watch` => This is normally wrap up the watching you've got nothing left to solve
- `rustlings verify` => This should do the same thing as the second suggestion

You could also upgrade version `4.2.0`.

Thanks,
Abdou

**Comment by AbdouSeck** [comment]
@AntonOellerer I was able to reproduce this issue. It seems like it does not have to do with the exercise itself but rather it's related to the way the `rustlings` decides when all the exercises have been completed. But since the `conversions` exercises are the last ones listed in the `info.toml` file, `rustlings` will decide that you have **_completed all the exercises_**, just because you completed the ones listed _last_ in the `info.toml`. This is a bug.

At first inspection, it looks like the bug is caused by [this line](https://github.com/rust-lang/rustlings/blob/26110da7cadc4ab7614730c2d0b1e514a2763d3d/src/main.rs#L224) that tries to fetch the pending exercises. That line basically fetches exercises that come after the least recently modified file. So, it assumes (wrongly) that you are following the order of exercises presented to you by the `watch` command.

In sum, the bug is reproducible if the user ignores the ordering provided by the `watch` command. If the last exercise listed in the `info.toml` file, then `watch` will get fooled into thinking that all the exercises have been solved.

I am working on a fix and will update this issue when the issue has been resolved.

Thanks,
Abdou
