### ISSUE TITLE
(quiz1) Explicit else required?

### ISSUE THREAD

**Issue by FFY00** [rust-lang/rustlings#596]
Hey, I am having trouble understanding the issue here :sweat_smile: 

When solving quiz1.

```rust
fn calculate_apple_price(num: i32) -> i32 {
    if num > 40 {
        num
    }
    num * 2
}
```
gives
```rustc
error[E0308]: mismatched types
  --> exercises/quiz1.rs:16:9
   |
15 | /     if num > 40 {
16 | |         num
   | |         ^^^ expected `()`, found `i32`
17 | |     }
   | |     -- help: consider using a semicolon here
   | |_____|
   |       expected this to be `()`
```

But if I add an explicit `else`, it passes.

```rust
fn calculate_apple_price(num: i32) -> i32 {
    if num > 40 {
        num
    } else {
        num * 2
    }
}
```

Why does this happen? What am I missing?

Thank you :blush:

**Comment by AbdouSeck** [comment]
@FFY00 this is a feature of the rust language that is not commonly found in many other languages. To be exact, `if-else` statements evaluate and _return_. For instance, the following works in rust, but not in `C`, `C++`, `Java` or even `Python`:

```rust
fn main() {
    let num = 5;
    let s = if num < 8 {
        "8 or higher, bro!"
    } else {
        "Now, we're talking"
    };
    // Now s contains the static string "8 or higher, bro!"
    println!("{}", s);
}
```
The issue is that if you only have an `if` statement without the `else`, [the contents of the body should evaluate to `()`](https://doc.rust-lang.org/stable/error-index.html#E0317). But the body of your _lone_ `if` statement evaluates to `num`. Hence, the compiler did not like that.

If you're looking for an early return, you can just use the `return` keyword in the body of the _lone_ `if` statement, as follows:
```rust
fn calculate_apple_price(num: i32) -> i32 {
    if num > 40 {
        return num;
    }
    num * 2
}
```
I hope you can now see why adding the `else` led to a correct program.

Please feel free to leave a comment if you have any more questions.

Thanks,
Abdou

**Comment by FFY00** [comment]
Ah, gotcha! I understand the semantics now. It makes sense, it's just not something I was expecting at first. Thank you :blush:

**Comment by rafaelnacle** [comment]
After finishing mine, I was looking for some more answers and I stumbled with this one: 
```
fn calculate_price_of_apples(amount: i32) -> i32 {
    amount * if amount > 40 { 1 } else { 2 }
}
```

Can someone explain what the amount * means ? or is a short way of multiplying the return of the if statement ?

**Comment by FFY00** [comment]
It's an inline `if`. They way it works in rust might be unexpected when coming from other languages, but essentially the whole `if ammount > 40 { 1 } else { 2 }` expression gets evaluated to `1` or `2`, resulting in `amount * 1` or `amount * 2`, respectively.

**Comment by rafaelnacle** [comment]
@FFY00 

Nice! I was suspecting it was that after looking for a while! Thanks for the reply and happy crabbing! 🦀
