### ISSUE TITLE
option/option1.rs needs extra constraints/clarification

### ISSUE THREAD

**Issue by doup** [rust-lang/rustlings#607]
If you read the exercise it just asks to compile. Which is not so difficult once you add a couple of `Some` and initialize the array. The thing is that you can just initialize the array with `[None; 5]`.

**But**, the hint speaks about `is_some, is_none, unwrap & match`, which are not needed at all to make this compile. I suspect the exercise wants me to handle a `numbers` array with a mixed bag of `None & Some`. Also, it looks like it expects me to handle `None` on `print_number` function, but it's not clear from the description.

<details>
  <summary>My solution (spoiler ⚠️)</summary>
  
```rust
// you can modify anything EXCEPT for this function's sig
fn print_number(maybe_number: Option<u16>) {
    if maybe_number.is_some() {
        println!("printing: {}", maybe_number.unwrap());
    } else {
        println!("printing: number is empty");
    }
}

fn main() {
    print_number(Some(13));
    print_number(Some(99));
    print_number(None);

    let mut numbers: [Option<u16>; 5] = [None, Some(1337), None, None, None];
    for iter in 0..5 {
        let number_to_add: u16 = {
            ((iter * 1235) + 2) / (4 * 16)
        };

        numbers[iter as usize] = match numbers[iter as usize] {
            Some(number) => Some(number),
            None => Some(number_to_add),
        };

        print_number(numbers[iter as usize]);
    }
}
```
  
</details>

**Comment by AbdouSeck** [comment]
@doup The exercise allows you to update everything **_EXCEPT_** the function signature of `print_number`. If you look at the definition of `print_number`, you'll see that it uses the `unwrap` method of the `Option` type. That should be an indication that whatever you end up passing to `print_number` should be an `Option` with a value in it. Otherwise, any compiled code would panic. As a result, the methods `is_some` and `is_none` should help with checking for such a condition. The `match` keyword should also help with figuring out whether or not an `Option` contains something.

The array initialization section is confusing and a bit out of place, indeed. But the goal with it is to make sure that **_you_** initialize the array with the right value. You have to initialize the array in order for it to be usable afterwards. Your solution seems to be doing that right.

In any case, the description of the exercise could definitely use some updating, and the hint could be retouched. But the following things are expected:

1. Edit the exercise so that it compiles without errors (do this without touching the definition of `print_number`)
2. Initialize the array so that the code below its definition compiles

You are welcome to submit a pull request with updates to the description and hint of the exercise.

Thank you,
Abdou

**Comment by doup** [comment]
Hi @AbdouSeck the following solution compiles (changes in code comments):

<details>
  <summary>Naive solution</summary>

```rust
// you can modify anything EXCEPT for this function's sig
fn print_number(maybe_number: Option<u16>) {
    println!("printing: {}", maybe_number.unwrap());
}

fn main() {
    print_number(Some(13)); // <======== add `Some`
    print_number(Some(99)); // <======== add `Some`

    let mut numbers: [Option<u16>; 5] = [None; 5]; // <======== initialise array
    for iter in 0..5 {
        let number_to_add: u16 = {
            ((iter * 1235) + 2) / (4 * 16)
        };

        numbers[iter as usize] = Some(number_to_add); // <======== add `Some`
    }
}
```
</details>

This compiles, although `print_number` doesn't handle `None`. This was my first solution to the exercise, but something looked weird, so I checked the hint and came with the solution from the previous comment.

I'm just raising this as a total Rust noob. Wouldn't it be more interesting to have a couple of tests so the user is required to handle `None` correctly?

Thanks anyway! :-)
