### ISSUE TITLE
Rustlings failing to build 'console' due to the non_exhaustive experimental feature

### ISSUE THREAD

**Issue by MHromiak** [rust-lang/rustlings#611]
Trying to download rustlings 4.3.0 for Ubuntu 20.04 with rustc 1.37.0-nightly (0af8e872e 2019-06-30), but when I try to run `curl -L https://git.io/rustlings | bash` I get the issue:

````
    Updating crates.io index
   Compiling console v0.14.0
error[E0658]: non exhaustive is an experimental feature
 --> /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/console-0.14.0/src/kb.rs:5:1
  |
5 | #[non_exhaustive]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/44109
  = help: add #![feature(non_exhaustive)] to the crate attributes to enable

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: failed to compile `rustlings v4.3.0 (/home/me/Desktop/rust/rustlings)`, intermediate artifacts can be found at `/home/me/Desktop/rust/rustlings/target`

Caused by:
  Could not compile `console`.
````

Being new to rust, I'm not sure how to fix this. I've tried changing the #[non_exhaustible] line in kb.rs, but get another error. How can this be resolved?

**Comment by AbdouSeck** [comment]
@MHromiak [this project's Cargo.toml file](https://github.com/rust-lang/rustlings/blob/main/Cargo.toml) requires the `v0.7.7` version of the `console` crate. If you're seeing compilation messages for `v0.14.0`, it could be because of the `indicatif` crate. Its corresponding [`Cargo.toml`](https://github.com/mitsuhiko/indicatif/blob/0.13.0/Cargo.toml) file lists the `console` crate as a dependency with versions between `0.9.1` and `1.0.0`. So, when building it, `cargo` pulled `console v0.14.0`, which satisfies that semver requirement.

Anyway, that is a long-winded way of saying that you're using a relatively old version of `rustc` that doesn't seem to support the `#[non_exhaustive]` directive on `enum` definitions. You're also using a nightly build, which doesn't play nicely with many published crates.

You can do one of two things:
- Upgrade to the latest versions of `rustc` (both stable and nightly). Or,
- You can clone both this project and the `indicatif` project. Then, change the `Cargo.toml` file of the `indicatif` project to set the version for `console` to `0.7.7`. After that, you also need to edit the `Cargo.toml` file of the `rustlings` project to point to the local copy of `indicatif`. Finally, you can install the `rustlings` binary with `cargo install`.

The following is a sample installation script with a couple of manual steps:
```bash
git clone https://github.com/mitsuhiko/indicatif.git
git clone https://github.com/rust-lang/rustlings.git
cd indicatif
# Use your editor to set the console dependency to: console = "0.7.7"
cd ../rustlings
# Use your editor to set the indicatif dependency to: indicatif = {path = "../indicatif"}
cargo install --force --path .
# Delete the local copy of indicatif if you want
rm -rf ../indicatif
# Call the rustlings binary
rustlings --help
```
Please give either one of the options above a try and let us know how it goes.

Thanks,
Abdou

**Comment by MHromiak** [comment]
Hi Abdou,

I actually ran across another post on stack overflow saying to do the same thing. I tried then, but rustup failed to update rustc's version. I tried a fresh reinstall of rust since you recommended the same procedure and it works! I don't know what it was with rustup, but rustc just refused to update, even if I overrode the local cache.

Cheers,

Markian
