### ISSUE TITLE
Automating rustlings initialization

### ISSUE THREAD

**Issue by arnabanimesh** [rust-lang/rustlings#612]
I have developed a [batch file](https://gist.github.com/arnabanimesh/b46b0a9f60b9ea7cb2ee3ae0eabc30e5) to automate the process for Windows using Windows Terminal and VSCode since it was becoming a chore to run it every time.

Maybe such files can be linked for some commonly used configurations in the README of this repo.

**Comment by GinoMan** [comment]
You can just put your terminal window on one side and the code on the other:

![image](https://user-images.githubusercontent.com/528834/228397374-3467c186-e3cc-4f39-ba75-78fad1e7baf2.png)

![image](https://user-images.githubusercontent.com/528834/228397512-231cb6c0-3f4d-4b8d-8d79-6b96b2e3d5c6.png)

It works great and you don't need wt (though I strongly recommend it since it is fantastic).

**Comment by mo8it** [comment]
Closing since it is too Windows specific and @GinoMan shows a way to do it with an editor like VS-Code :)
