### ISSUE TITLE
move_semantics5 makes use of "*", which has not been explained yet

### ISSUE THREAD

**Issue by dtaralla** [rust-lang/rustlings#809]
This exercise could use a refactor where we don't use the `*` operator. The `*` is confusing/distracting at this stage for beginners. Moreover, the readme for the move_semantics section doesn't link to any page explaining what `*` does.
Couldn't we use String or Vec like in the [linked docs](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html) instead of playing with dereferencing references to a variable on the stack?

**Comment by bm0** [comment]
+1 I see two mutable refs to `x` in this exercise.
But it impossible by rust design.

Why it works?
```rust
fn main() {
    let mut x = 100;
   
    let y = &mut x;
    let z = &mut *y;
    // y and z is mutable references to x at the same time, it isn't?
   
    *y += 100;
    *z += 1000;
    assert_eq!(x, 1200);
}
```

**Comment by LeoniePhiline** [comment]
@bm0 It does not work though (on purpose):

```
error[E0503]: cannot use `*y` because it was mutably borrowed
 --> src/main.rs:8:5
  |
5 |     let z = &mut *y;
  |             ------- borrow of `*y` occurs here
...
8 |     *y += 100;
  |     ^^^^^^^^^ use of borrowed `*y`
9 |     *z += 1000;
  |     ---------- borrow later used here
```

Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7a19b93609ece84708875c8eb375e722

The point of the exercise is making it work by reordering:

```rust
fn main() {
    let mut x = 100;
   
    let y = &mut x;
    *y += 100;
    let z = &mut *y;
    *z += 1000;
    assert_eq!(x, 1200);
}
```
Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bd6d10a01a666cd7bc6c63ff961e64f4

**This is possible because the `y` and `z` references are no longer used after the mutations, and are dropped.**

**The borrow checker will refuse compilation if you do use `y` and `z` later again,**
e.g. if you add `println!("{} {} {}", x, y, z);` to the end of the function:

```rust
error[E0502]: cannot borrow `x` as immutable because it is also borrowed as mutable
 --> src/main.rs:9:26
  |
4 |     let y = &mut x;
  |             ------ mutable borrow occurs here
...
9 |     println!("{} {} {}", x, y, z);
  |                          ^  - mutable borrow later used here
  |                          |
  |                          immutable borrow occurs here

error[E0502]: cannot borrow `y` as immutable because it is also borrowed as mutable
 --> src/main.rs:9:29
  |
6 |     let z = &mut *y;
  |             ------- mutable borrow occurs here
...
9 |     println!("{} {} {}", x, y, z);
  |                             ^  - mutable borrow later used here
  |                             |
  |                             immutable borrow occurs here

error[E0502]: cannot borrow `x` as immutable because it is also borrowed as mutable
 --> src/main.rs:8:5
  |
4 |     let y = &mut x;
  |             ------ mutable borrow occurs here
...
8 |     assert_eq!(x, 1200);     
  |     ^^^^^^^^^^^^^^^^^^^^ immutable borrow occurs here
9 |     println!("{} {} {}", x, y, z);
  |                             - mutable borrow later used here
  |
  = note: this error originates in the macro `assert_eq` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by bm0** [comment]
@LeoniePhiline I edited my previous message, now example is works.

**Comment by bm0** [comment]
@LeoniePhiline it's called freezing, isn't it?
This topic isn't covered in the rust book.

**Comment by bm0** [comment]
@LeoniePhiline thanks a lot!

**Comment by LeoniePhiline** [comment]
@bm0 Very welcome :)

**Comment by FellowSolicist** [comment]
I think the intent of the original post was lost a bit. I'm a beginner going through the rustlings exercises and I was completely derailed by this exercise because I had no clue what the `*` operator was. Like @dtaralla said, the [linked documentation](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html#mutable-references) 
 in the `hint` text simply says.
 
>  We’ll see some uses of the dereference operator in Chapter 8 and discuss details of dereferencing in Chapter 15.

It seems backwards to require an understanding of a concept from Chapter 15 to complete an exercise meant to teach the basics of ownership.

 I found this thread in a google search looking for an explanation for this exercise and the `*` operator. Thanks @LeoniePhiline for the break down, it was very helpful

**Comment by boabdilperez** [comment]
> I think the intent of the original post was lost a bit. I'm a beginner going through the rustlings exercises and I was completely derailed by this exercise because I had no clue what the `*` operator was. Like @dtaralla said, the [linked documentation](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html#mutable-references)
> in the `hint` text simply says.
> 
> > We’ll see some uses of the dereference operator in Chapter 8 and discuss details of dereferencing in Chapter 15.
> 
> It seems backwards to require an understanding of a concept from Chapter 15 to complete an exercise meant to teach the basics of ownership.
> 
> I found this thread in a google search looking for an explanation for this exercise and the `*` operator. Thanks @LeoniePhiline for the break down, it was very helpful

I am in exactly the same position as you. Even if the solution doesn't require you to really understand dereferencing to solve it, it's a wholly unnecessary distraction. Especially with the compiler throwing an error on the line with the * operator, you are led to believe you need to know something about how it works in order to fix the error. This is badly written- if it's really supposed to be for beginners.

**Comment by LeoniePhiline** [comment]
I personally found that it nicely makes beginners dive into research to proactively find answers themselves. It’s a great way to discover the rust book and other documentation. 

If you use [the usual rustlings hint](https://github.com/rust-lang/rustlings/blob/main/info.toml) (contents at around line 220) you are led to the [References and borrowing](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html) page. 

This page provides the solution:

> Note: The opposite of referencing by using `&` is dereferencing, which is accomplished with the dereference operator, `*`.

**Comment by boabdilperez** [comment]
That doesn't actually provide the solution, though? The solution is to re-order the existing code. 

The instructions on that tutorial page, the instructions in the readme, and the hint all provide conflicting information as to what is important about solving that lesson. The lesson isn't one on research or documentation, it's a single lesson in a set of lessons that are all about the concept of passing ownership around a program.

Learning to navigate the rust docs is undoubtedly an important skill, but that's clearly not the intent here.

**Comment by mo8it** [comment]
Fixed in https://github.com/rust-lang/rustlings/commit/d7024d80ce0a640271d006dbfda440f60652af6d
