### ISSUE TITLE
Easy way to skip exercises

### ISSUE THREAD

**Issue by python128** [rust-lang/rustlings#855]
I have noticed that anyone can skip the exercises that have to be `compiled` by just commenting out the entire code. 
Since there is nothing to run, it will compile successfully, and move on to the next exercise. 

Any way to stop this?

**Comment by diannasoriel** [comment]
Not really, just don't do it. Rustlings is basically entirely based around good faith, if you skip the exercises you'll learn nothing 🤷‍♀️

**Comment by SharmaTushar1** [comment]
This is closed but I wanted to add one thing to this. So, for variables exercise it's initially this

<img width="1160" height="1698" alt="Image" src="https://github.com/user-attachments/assets/ba78d8aa-9a03-4582-b64f-7293031109a0" />

I changed the value of the variable to 10.

<img width="1106" height="1426" alt="Image" src="https://github.com/user-attachments/assets/7e3a3c2d-f9b7-45a7-85df-85ac0de0714f" />

I'm not sure if that's the expected answer. This problem is pretty simple and is one of the first exercises so I believe (maybe?) this is the right way. But, I believe this can be an issue in future cases. Where we're able to successfully compile the code in an exercise without achieving the right solution. Not intentionally (like commenting) but just by mistake. And assuming that it's the right solution and moving to the next one.

**Comment by SharmaTushar1** [comment]
nvm. I now see the `help` in the output of my first screenshot. Missed it earlier. I think that should be good to guide on what's expected. Will leave my comments here. In case anyone else missed it and is checking the issues 😬
