### ISSUE TITLE
Creating exercises with dependencies

### ISSUE THREAD

**Issue by dabreegster** [rust-lang/rustlings#897]
@Robinlovelace and I are interested in creating a bunch of exercises to teach people how to use some https://github.com/georust/geo crates. Right now, none of the exercises pull in any external dependencies, and adding the dependencies to `Cargo.toml` in the repo has no effect -- because that's for the `rustlings` tool itself. I really quickly dug around to figure out how the tool compiles each exercise and found https://github.com/rust-lang/rustlings/blob/e06ba1df58a4bc3a8ccbbd11c8a393cf98a875db/src/exercise.rs#L119. It looks like we could write a temporary `Cargo.toml` file for the exercise to glue in some dependencies. I'm curious if anybody here has thought about doing this before (but didn't spot any issues) and if there's an opinion how to support it, possibly as a hack in a fork of this repo, but ideally as some kind of configuration for sets of exercises. Thanks!

**Comment by dabreegster** [comment]
#448 may be related

**Comment by diannasoreil** [comment]
Yeah, #448 is related, and this is a longstanding architectural question. Personally, I don't feel like it's very important, because Rustlings is intentionally not about teaching you Cargo, and not about teaching you your editor integration, but if we managed to come up with a satisfactory implementation for this that's not too backwards-incompatible, I'd be open for pulling it in.

**Comment by mo8it** [comment]
Closing because that should be easy after https://github.com/rust-lang/rustlings/issues/1935

About `geo` exercises, that should be covered by https://github.com/rust-lang/rustlings/issues/1936

**Comment by Robinlovelace** [comment]
Fanastic, many thank!
