### ISSUE TITLE
Exercise 'error5' - enum custom error texts not showing in console (even tough defined) when providing zero or a negative arg

### ISSUE THREAD

**Issue by itayperry** [rust-lang/rustlings#973]
After solving the exercise (with `Box<dyn error::Error>`) **everything works fine** but the error messages defined here: 

https://github.com/rust-lang/rustlings/blob/d2179d3e8442ca3ecd24738e2fa41b31023120e5/exercises/error_handling/errors5.rs#L43-L53

are not showing in the console when assigning 0/a negative (inside a string) in here:

https://github.com/rust-lang/rustlings/blob/d2179d3e8442ca3ecd24738e2fa41b31023120e5/exercises/error_handling/errors5.rs#L15

All you can see in the console  is:

### **Error: Negative**
or
### **Error: Zero**

The thing is - if you write:
```rust
println!("creation error negative text is: {}", CreationError::Negative);
```

inside `fn main()` you'll see this printed in the console: `creation error negative text is: number is negative`

Is this a bug? 

And of course thank you for `rustlings` - it's just incredible! It makes learning Rust fun 🎉

**Comment by mo8it** [comment]
This is working as intended. If the `main` function returns an `Err`, then it is printed using the `fmt::Debug` implementation which is derived for `CreationError` in the exercise.

You can see how a `Result` is handled as a return type of the `main` function: [Implementation of the `Termination` trait for `Result`](https://github.com/rust-lang/rust/blob/649feb9c1a3c56650a4b6fa638b23103cbcd0dcd/library/std/src/process.rs#L2468-L2478)

`Display` is implemented in the exercise because the `Error` trait requires it.
